# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SearchRepositoryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire'

  # Pods for SearchRepositoryApp

  target 'SearchRepositoryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchRepositoryAppUITests' do
    # Pods for testing
  end

end
